---
  - name: Ensure the PGP key is installed
    apt_key: id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"
    sudo: true

  - name: Ensure https support for apt is installed
    apt: pkg=apt-transport-https state=present
    sudo: true

  - name: Ensure the passenger apt repository is added
    apt_repository: state=present repo="deb https://download:{{ passenger_enterprise_key }}@www.phusionpassenger.com/enterprise_apt {{ passenger_ubuntu_version }} main"
    sudo: true

  - name: Ensure nginx is installed
    apt: pkg=nginx-extras state=present
    sudo: true

  - name: Ensure passenger is installed
    apt: pkg=passenger-enterprise state=present update_cache=yes
    sudo: true
